Added 3 breakpoints
0ka3ri/uncanny-page pull request #19
Opened 2024-05-20 02:08 UTC by 0ka3ri

I think the general design might be somewhat okay though I read it's recommended to use min-width on media queries instead of max-width, but I never know if I can trust the source of the comment whenever I search online for best practices. 

I'm having trouble finding out why does the hamburger icon displays well on the home page and not on every other sub page, because it's exactly the same header on each file. I have been reading the whole code for a while and still can't find the reason, I suspect it might be related to the selectors but I don't know how. 

I also have a small question regarding the order of the imported style sheets. Should the base sheet be first rather than the responsive one or is it irrelevant? I figure since the code is read in order I should probably change it because the base sheet is more important and should load first.

2024-05-20 12:39 UTC, 0ka3ri commented
I solved the hamburger issue by tagging  _header img.hamburger-menu_ instead of _header.hamburger-menu_ or _header .hamburger-menu_. I still think I'm probably doing something wrong because I still don't understand the reason why 

```
header .hamburger-menu {
  display: block;
}
```
worked but ONLY on home page. I'll make the commit later.

2024-05-21 22:17 UTC, 0ka3ri commented
On the latest commit you'll find a new bug on the print media query: the Hamburger Icon displays on the print sheet and the Index Title doesn't, when it should be the other way around (on the style.css sheet the first one is hidden and the second one is visible). 
I will optimize this media query after the deployment, adding paper size adjustments and others.

As I said before, I also fixed the display of the Hamburger Icon on the subpages but a general feedback on the latest changes would be much appreciated (:

2024-05-25 02:23 UTC, mauriciopasquier requested changes
Very nice responsive menu! Check out these comments and it'll be ready to merge.

2024-05-25 02:23 UTC, mauriciopasquier commented on README.md
> +This is my first personal project on HTML, CSS and JavaScript. It's a minimalist page with information about cognitive baias and psychological paradoxes.
baia baia

2024-05-25 02:23 UTC, mauriciopasquier commented on about/index.html
> +          width="40" height="1000"
This is too much height.

2024-05-25 02:23 UTC, mauriciopasquier commented on base-rate-fallacy/index.html
> +          width="40" height="1000"
Height

2024-05-25 02:23 UTC, mauriciopasquier commented on base-rate-fallacy/index.html
> +          <li><a href="self-fulfilling-prophesy/index.html">Self Fulfilling Prophecy</a></li>
I think all these href should point to the base folder, right? With `../`

2024-05-25 02:23 UTC, mauriciopasquier commented on contact/index.html
> +          width="40" height="1000"
Height

2024-05-25 03:17 UTC, mauriciopasquier commented
> On the latest commit you'll find a new bug on the print media query: the Hamburger Icon displays on the print sheet and the Index Title doesn't, when it should be the other way around (on the style.css sheet the first one is hidden and the second one is visible).
> I will optimize this media query after the deployment, adding paper size adjustments and others.

I forgot about this issue. You have to restore back the `display: flex` on `.index-title` and hide the `.hamburguer-menu` on this media query.

2024-05-26 23:33 UTC, mauriciopasquier approved these changes

2024-05-27 00:50 UTC, merged