Pre-deployment
0ka3ri/uncanny-page pull request #28
Opened 2024-07-08 00:03 UTC by 0ka3ri

Changed relative paths to absolute and moved style.css to Styles folder

2024-07-08 04:01 UTC, mauriciopasquier requested changes

2024-07-08 04:01 UTC, mauriciopasquier commented on subpages/about/index.html
> +          <li><a href="/subpages/base-rate-fallacy/index.html">Base Rate Fallacy</a></li>
You missed all these /index.html

2024-07-08 04:02 UTC, mauriciopasquier commented on subpages/about/index.html
> +          <li><a href="/subpages/base-rate-fallacy/index.html">Base Rate Fallacy</a></li>
I think most of the href still use `/index.html`? I thought the idea was to remove them as well.

2024-07-08 16:17 UTC, 0ka3ri commented on subpages/about/index.html
> +          <li><a href="/subpages/base-rate-fallacy/index.html">Base Rate Fallacy</a></li>
Just wanted to see if you were paying attention :eyes:

2024-07-10 00:42 UTC, 0ka3ri commented on subpages/about/index.html
> +          <li><a href="/subpages/base-rate-fallacy/index.html">Base Rate Fallacy</a></li>
Done!

2024-07-10 15:37 UTC, mauriciopasquier approved these changes

2024-07-10 15:38 UTC, mauriciopasquier commented
I didn't test it but it looks good!

2024-07-10 15:42 UTC, 0ka3ri commented
> I didn't test it but it looks good!

_"We didn't playtest this at all"_

2024-07-10 20:02 UTC, merged