Style design
0ka3ri/uncanny-page pull request #3
Opened 2024-04-25 00:26 UTC by 0ka3ri

I made the first additions on the CSSs design.

2024-04-25 00:56 UTC, mauriciopasquier requested changes
This looks really nice!

In general, I would try to take advantage of [semantic tags](https://www.w3.org/QA/Tips/goodclassnames) in the html when possible. What I mean is that, for example, instead of adding a `"ul-index"` class to the `ul` element, just say it's an `"index"` and use `ul.index` as the CSS selector. Same for `"anchors-index"` (this should be singular by the way, you're saying "this element is an anchor"). Or better yet, say the `menu` is an `index` and use `menu.index ul a` as a selector if you want to style the `a`. Alternatively, you could use just class names if you want to be independent of the specific elements, but using the element name inside the class name is the worst of both worlds.

I also left a couple of syntax comments.

2024-04-25 00:56 UTC, mauriciopasquier commented on index.html
> +    <link rel ="stylesheet" href="style.css">
Don't leave spaces before `=`

2024-04-25 00:56 UTC, mauriciopasquier commented on style.css
> +  display:flex;
Leave a space after `:` :P

2024-04-25 19:28 UTC, espimadrazo commented on style.css
> +  display:flex;
There, I fixed it.

2024-04-26 00:58 UTC, mauriciopasquier approved these changes

2024-04-26 01:02 UTC, merged