File restructuring & robots.txt file
0ka3ri/uncanny-page pull request #33
Opened 2024-08-20 00:28 UTC by 0ka3ri

Closes #30, closes #32 

I moved the subpages folders into the root folder and I created the robot.txt in which I restricted chatGPT access to the whole website.

2024-08-20 02:57 UTC, mauriciopasquier requested changes

2024-08-20 02:57 UTC, mauriciopasquier commented on about/index.html
> +          <li><a href="/subpages/self-fulfilling-prophesy">Self Fulfilling Prophecy</a></li>
You need to remove `/subpages` from everything, turning 

```
/subpages/self-fulfilling-prophesy
```

Into

```
/self-fulfilling-prophesy
```

Sounds like a lot but it is a good opportunity to learn your editor's (or a linux console tool's) search and replace feature :P

2024-08-20 02:57 UTC, mauriciopasquier commented on robots.txt
> +User-agent: *
I think the default is to allow, so you only need the lines 5 and 6 for this behavior.

2024-08-23 22:59 UTC, 0ka3ri commented
Done!

2024-08-23 23:56 UTC, mauriciopasquier approved these changes

2024-08-24 00:06 UTC, merged